export default ActionTypes = {
    LOGINREQUEST: "LOGINREQUEST",
    LOGINREQUESTSUCCESS: "LOGINREQUESTSUCCESS",
    LOGINREQUESTFAILED: "LOGINREQUESTFAILED",

    SIGNUPREQUEST: "SIGNUPREQUEST",
    SIGNUPREQUESTSUCCESS: "SIGNUPREQUESTSUCCESS",
    SIGNUPREQUESTFAILED: "SIGNUPREQUESTFAILED",

    ADDREQUEST: "ADDREQUEST",
    ADDREQUESTSUCCESS: "ADDREQUESTSUCCESS",
    ADDREQUESTFAILED: "ADDREQUESTFAILED",

    VIEWREQUEST: "VIEWREQUEST",
    VIEWREQUESTSUCCESS: "VIEWREQUESTSUCCESS",
    VIEWREQUESTFAILED: "VIEWREQUESTFAILED",

    SEARCHREQUEST: "SEARCHREQUEST",
    SEARCHREQUESTSUCCESS: "SEARCHREQUESTSUCCESS",
    SEARCHREQUESTFAILED: "SEARCHREQUESTFAILED",

}